@startuml manage_balance

package transactionController <<Folder>> {
  
  class RefillMoneyInputController{
    +refillBalance()
  }
  class pullOutMoneyInputController{
    +pullOutMoney()
  }
}

package transaction <<Folder>> {
  class TransactionFaçade {
    +getInstance() : TransactionFaçade
    +refillBalance(CreditCard creditcard, Float amount)
    +pullOutMoneyFromAccount(BankAccount account, Float amount)
  }
  
}

package dao <<Folder>> {

  class DAOFactory {
    #{static}connection : Connection
    +createTransactionDao() : TransactionDao
    +{static}getConnection() : Connection
  }

  package mysql <<Folder>> {
    class MySqlDAOFactory {}
    class MySqlTransactionDAO {}
    
    MySqlDAOFactory .down.> MySqlTransactionDAO : creates
  }
  
  package postgres <<Folder>> {
    class MyPostGresDAOFactory {}
    class MyPostGresTransactionDAO {}
    
    MyPostGresDAOFactory .down.> MyPostGresTransactionDAO : creates
  }
  
  
  class TransactionDAO {
    +getConnection() : Connection
    +createBankAccountToUserTransactiont(CreditCard creditCard, Float amount): Transaction
    +createUserToBankAccountTransactiont(BankAccount account, Float amount): Transaction
  }

  DAOFactory <|-- MySqlDAOFactory
  DAOFactory <|-- MyPostGresDAOFactory    
  TransactionDAO <|-- MyPostGresTransactionDAO
  TransactionDAO <|-- MySqlTransactionDAO

}

RefillMoneyInputController .down.> TransactionFaçade
pullOutMoneyInputController .down.> TransactionFaçade

TransactionFaçade -down-> DAOFactory
TransactionFaçade -down-> TransactionDAO

@enduml