@startuml

autonumber


[-> RefillMoneyInputController : refillBalance()

RefillMoneyInputController -> TransactionFacade: refillBalance(BankAccount,Float)

TransactionFacade -> DAOFactory: createTransactionDAO()
DAOFactory -> TransactionDAO : creates

activate TransactionDAO

TransactionDAO -> DAOFactory : TransactionDAO
DAOFactory -> TransactionFacade : TransactionDAO
TransactionFacade -> TransactionDAO : createBankAccountToUserTransaction(CreditCard,Float)

deactivate TransactionDAO

@enduml