@startuml
autonumber

ChangePasswordController -> ValidationController : tempUser.setPassword(String)
ChangePasswordController -> SplitPay : window.setScene(new Scene(Parent, int, int))

ChooseValidationMethodController -> UserFacade : getVerifiedPhone()
UserFacade -> UserDAO : getVerifiedPhone()
alt user has a verified phone
    UserDAO --> ChooseValidationMethodController : phone
else verified phone = null
    UserDAO --> ChooseValidationMethodController : exception
end
ChooseValidationMethodController -> UserFacade : getVerifiedEmail()
UserFacade -> UserDAO : getVerifiedEmail()
alt user has a verified email
    UserDAO --> ChooseValidationMethodController : email
else verified email = null
    UserDAO --> ChooseValidationMethodController : exception
end
ChooseValidationMethodController -> ValidationController : isPhoneValidationMethod(Boolean);

ChooseValidationMethodController -> SplitPay : window.setScene(new Scene(Parent, int, int))

ValidationController -> ValidationController : generateValidationCode()
ValidationController -> ValidationController : sendValidationCode()
alt success
    ValidationController -> UserFacade : updateUser(tempUser)
    activate UserDAO
    UserFacade -> UserDAO : update(User)
    UserDAO --> ValidationController : done
    deactivate UserDAO
else wrong validation code
    <-- ValidationController : wrong code, please retry
end
ValidationController -> SplitPay : window.setScene(new Scene(Parent, int, int))

@enduml